<h2>Cross Validation</h2>

In [1]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits
import warnings
warnings.filterwarnings('ignore')



In [2]:
dt = load_digits()
dir(dt)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [3]:
data = pd.DataFrame(dt.data)
data
X = data
X

0    1     2     3     4     5    6    7    8    9   ...   54   55  \
0     0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...   
1792  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  4.0  0.0   
1793  0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  1.0  0.0   
1794  0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1795  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  2.0  0.0   
1796  0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  8.0  0.0   

       56   57   58    59    60    61   62   63  
0     0.0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1     0.0  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2     0.0  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3     0.0  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4     0.0  0.0  0.0   2.0  16.0   4.0  0.0  0.0  
...   ...  ...  ...   ...   ...   ...  ...  ...  
1792  0.0  0.0  2.0  14.0  15.0   9.0  0.0  0.0  
1793  0.0  0.0  6.0  16.0  14.0   6.0  0.0  0.0  
1794  0.0  0.0  2.0   9.0  13.0   6.0  0.0  0.0  
1795  0.0  0.0  5.0  12.0  16.0  12.0  0.0  0.0  
1796  0.0  1.0  8.0  12.0  14.0  12.0  1.0  0.0  

[1797 rows x 64 columns]

In [4]:
data["target"] = dt.target
y = data.iloc[: , 64:]
y

target
0          0
1          1
2          2
3          3
4          4
...      ...
1792       9
1793       0
1794       8
1795       9
1796       8

[1797 rows x 1 columns]

In [5]:
#creating a model with DecisionTree

dtc = DecisionTreeClassifier()

In [6]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(X , y , test_size = 0.3)

In [7]:
len(x_train)

1257

In [8]:
len(x_test)

540

In [9]:
dtc.fit(x_train , y_train)

DecisionTreeClassifier()

In [10]:
dtc.score(x_test , y_test)

1.0

In [11]:
#using logistic regression
ltr = LogisticRegression()

In [12]:
ltr.fit(x_train , y_train)

LogisticRegression()

In [13]:
ltr.score(x_test , y_test)

0.9814814814814815

In [14]:
#for support vector machines 

sv = SVC()

In [15]:
sv.fit(x_train , y_train)

SVC()

In [16]:
sv.score(x_test , y_test)

0.9907407407407407

In [17]:
rf = RandomForestClassifier(n_estimators = 40)

In [18]:
rf.fit(x_train , y_train)

RandomForestClassifier(n_estimators=40)

In [19]:
rf.score(x_test , y_test)

0.9944444444444445

In [20]:
from sklearn.model_selection import  KFold

In [21]:
kv = KFold(n_splits=3)

In [22]:
for train_index , test_index in kv.split([1,2,3,4,5,6,7,8,9]):
    print(train_index , test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [23]:
def get_score(model , x_train ,x_test, y_train ,y_test):
    model.fit(x_train , y_train)
    return model.score(x_test , y_test)

In [24]:
get_score(LogisticRegression(),x_train ,x_test, y_train ,y_test)

0.9814814814814815

In [25]:
from sklearn.model_selection import StratifiedKFold

In [26]:
sk = StratifiedKFold(n_splits = 3)

In [27]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index ,test_index in kv.split(dt.data):
    x_train  , x_test , y_train , y_test = dt.data[train_index] , dt.data[test_index],\
                                            dt.target[train_index] , dt.target[test_index]
    scores_l.append(get_score(LogisticRegression(),x_train ,x_test, y_train ,y_test))
    scores_svm.append(get_score(SVC(),x_train ,x_test, y_train ,y_test))
    scores_rf.append(get_score(RandomForestClassifier(),x_train ,x_test, y_train ,y_test))
    

    
    
    

In [28]:
scores_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [29]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [30]:
scores_rf

[0.9365609348914858, 0.9532554257095158, 0.9315525876460768]

In [31]:
from sklearn.model_selection import cross_val_score

In [32]:
cross_val_score(LogisticRegression() , dt.data  , dt.target)

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [33]:
cross_val_score(SVC() , dt.data  , dt.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [34]:
cross_val_score(RandomForestClassifier(n_estimators=40) , dt.data  , dt.target)

array([0.93055556, 0.90833333, 0.94986072, 0.94707521, 0.93314763])

<h2>Exercise</h2>

In [71]:
from sklearn.model_selection import KFold
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [36]:
data = pd.read_csv("diabetes.csv")

In [37]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0          6.0      148             72             35        0  33.6   
1          1.0       85             66             29        0  26.6   
2          8.0      183             64              0        0  23.3   
3          1.0       89             66             23       94  28.1   
4          0.0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [38]:
#logisticregression 
lr = LogisticRegression()
lr

LogisticRegression()

In [50]:
#decision tree
dtree = DecisionTreeClassifier(criterion="gini")
dtree

DecisionTreeClassifier()

In [51]:
#random tree
randomTree = RandomForestClassifier()
randomTree

RandomForestClassifier()

In [52]:
#support vector machine 
supportVec = SVC()
supportVec

SVC()

In [53]:
X = data.drop("Outcome" , axis = "columns")
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6.0      148             72             35        0  33.6   
1            1.0       85             66             29        0  26.6   
2            8.0      183             64              0        0  23.3   
3            1.0       89             66             23       94  28.1   
4            0.0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763         10.0      101             76             48      180  32.9   
764          2.0      122             70             27        0  36.8   
765          5.0      121             72             23      112  26.2   
766          1.0      126             60              0        0  30.1   
767          1.0       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [54]:
 y = data.iloc[: , 8]
 y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [55]:
x_train , x_test , y_train , y_test = train_test_split(X,y,test_size = 0.2)

In [56]:
len(x_train)

614

In [57]:
len(x_test)

154

In [67]:
crossVal_train = cross_val_score(dtree , x_train , y_train , scoring="accuracy" , cv=5)

In [68]:
crossVal_test = cross_val_score(dtree , x_test , y_test , scoring="accuracy" , cv=5)

In [69]:
crossVal_train

array([0.64227642, 0.61788618, 0.65853659, 0.62601626, 0.68852459])

In [70]:
crossVal_test

array([0.77419355, 0.67741935, 0.83870968, 0.64516129, 0.76666667])

In [72]:
np.mean(crossVal_train)

0.6466480074636812

In [73]:
np.mean(crossVal_test)

0.7404301075268818