In [9]:
#import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
import numpy as np

In [10]:
df_house = pd.read_csv("Housing_data.csv")

In [11]:
df_house["location"].unique()

array(['gbagada', 'surulere', 'yaba', 'ikorodu', 'ogba', 'iyanaipaja',
       'ikeja', 'ikoyi', 'ajah', 'lekki'], dtype=object)

In [3]:
df_house.head()

price  bedrooms  bathrooms  toilets  estate_flag  terrace_flag  \
0   850000.0       3.0        2.0      3.0          0.0           0.0   
1   650000.0       1.0        1.0      1.0          1.0           0.0   
2   600000.0       2.0        2.0      2.0          0.0           0.0   
3  1500000.0       3.0        3.0      4.0          1.0           0.0   
4  1500000.0       3.0        3.0      3.0          1.0           0.0   

   new_flag  serviced_flag  location_rank  exec_flag  estate_price  \
0       0.0            0.0           31.0        1.0     1300000.0   
1       1.0            1.0            9.0        1.0      400000.0   
2       0.0            0.0           26.0        1.0      800000.0   
3       0.0            0.0           31.0        2.0     1300000.0   
4       0.0            0.0           31.0        2.0     1300000.0   

   serviced_price  new_price locationbed location  \
0       1840000.0  1840000.0    gbagada3  gbagada   
1        560000.0   560000.0    gbagada1  gbagada   
2       1060000.0  1060000.0    gbagada2  gbagada   
3       1840000.0  1840000.0    gbagada3  gbagada   
4       1840000.0  1840000.0    gbagada3  gbagada   

                          spec_location  \
0          sosanya soluyi gbagada lagos   
1           millenuim ups gbagada lagos   
2                 alapere gbagada lagos   
3                  medina gbagada lagos   
4  adeola atunrase medina gbagada lagos   

                                         description  
0  3 bedroom Flat / Apartment for rent Sosanya So...  
1  1 bedroom mini flat Mini flat Flat / Apartment...  
2          2bed at Alapere, all rooms ensuit ... ...  
3  3 bedroom Flat / Apartment for rent Medina Gba...  
4  3 bedroom House for rent Adeola Atunrase Medin...

In [4]:
df_house.drop(["locationbed" , "spec_location" , "description" ] ,  axis = "columns" , inplace = True)

In [8]:
df_house["location"].unique()

array([1, 8, 9, 3, 7, 5, 2, 4, 0, 6])

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le

LabelEncoder()

In [6]:
df_house["location"] = le.fit_transform(df_house["location"])

In [7]:
df_house["location"]

0       1
1       1
2       1
3       1
4       1
       ..
4372    6
4373    6
4374    6
4375    6
4376    6
Name: location, Length: 4377, dtype: int32

In [8]:
X = df_house.iloc[: , 1: 14].values
X

array([[3.00e+00, 2.00e+00, 3.00e+00, ..., 1.84e+06, 1.84e+06, 1.00e+00],
       [1.00e+00, 1.00e+00, 1.00e+00, ..., 5.60e+05, 5.60e+05, 1.00e+00],
       [2.00e+00, 2.00e+00, 2.00e+00, ..., 1.06e+06, 1.06e+06, 1.00e+00],
       ...,
       [4.00e+00, 5.00e+00, 5.00e+00, ..., 4.50e+06, 4.50e+06, 6.00e+00],
       [5.00e+00, 5.00e+00, 6.00e+00, ..., 6.50e+06, 6.50e+06, 6.00e+00],
       [3.00e+00, 3.00e+00, 4.00e+00, ..., 3.50e+06, 3.50e+06, 6.00e+00]])

In [9]:
y = df_house.iloc[: , 0]
y

0        850000.0
1        650000.0
2        600000.0
3       1500000.0
4       1500000.0
          ...    
4372    4000000.0
4373    6000000.0
4374    7000000.0
4375    4500000.0
4376    1200000.0
Name: price, Length: 4377, dtype: float64

In [11]:
#features in selection
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [14]:
#apply SelectKBest class to extract top 10 best features
bestfeatures = SebeflectKBest(score_func=chi2, k=10)
fit = bestfeatures.fit(X,y)
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(df_house.iloc[: , 1:14].columns)

In [15]:
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']  #naming the dataframe columns
print(featureScores.nlargest(10,'Score'))  #print 10 best features

             Specs         Score
10  serviced_price  4.490097e+09
11       new_price  4.490097e+09
9     estate_price  3.648917e+09
7    location_rank  2.479423e+04
8        exec_flag  1.901624e+03
4     terrace_flag  1.644899e+03
2          toilets  1.308640e+03
0         bedrooms  1.246457e+03
1        bathrooms  9.908438e+02
12        location  4.881536e+02


In [19]:
#now getting the my data split
X = df_house[["bathrooms" , "serviced_price" , "new_price" , "estate_price" , "location_rank","exec_flag" , "terrace_flag" , "toilets" , "bedrooms" , "location"]].values
X

array([[2.00e+00, 1.84e+06, 1.84e+06, ..., 3.00e+00, 3.00e+00, 1.00e+00],
       [1.00e+00, 5.60e+05, 5.60e+05, ..., 1.00e+00, 1.00e+00, 1.00e+00],
       [2.00e+00, 1.06e+06, 1.06e+06, ..., 2.00e+00, 2.00e+00, 1.00e+00],
       ...,
       [5.00e+00, 4.50e+06, 4.50e+06, ..., 5.00e+00, 4.00e+00, 6.00e+00],
       [5.00e+00, 6.50e+06, 6.50e+06, ..., 6.00e+00, 5.00e+00, 6.00e+00],
       [3.00e+00, 3.50e+06, 3.50e+06, ..., 4.00e+00, 3.00e+00, 6.00e+00]])

In [20]:
y

0        850000.0
1        650000.0
2        600000.0
3       1500000.0
4       1500000.0
          ...    
4372    4000000.0
4373    6000000.0
4374    7000000.0
4375    4500000.0
4376    1200000.0
Name: price, Length: 4377, dtype: float64

In [69]:
#using the train and split method for modelling 

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import pickle

In [60]:
lm = LinearRegression()

In [61]:
x_train , x_test , y_train , y_test = train_test_split(X , y , test_size = 0.2)

In [62]:
x_train

array([[2.0e+00, 5.7e+05, 5.7e+05, ..., 2.0e+00, 1.0e+00, 0.0e+00],
       [0.0e+00, 4.5e+06, 4.5e+06, ..., 0.0e+00, 4.0e+00, 6.0e+00],
       [1.0e+00, 1.5e+06, 1.5e+06, ..., 1.0e+00, 1.0e+00, 6.0e+00],
       ...,
       [2.0e+00, 7.9e+06, 7.9e+06, ..., 3.0e+00, 2.0e+00, 4.0e+00],
       [4.0e+00, 4.5e+06, 4.5e+06, ..., 5.0e+00, 4.0e+00, 6.0e+00],
       [4.0e+00, 4.5e+06, 4.5e+06, ..., 4.0e+00, 4.0e+00, 6.0e+00]])

In [63]:
y_train

1714     500000.0
2801    4000000.0
3606    1500000.0
2247     600000.0
905      250000.0
          ...    
1844    1000000.0
2423    2800000.0
1639    4500000.0
2388    3500000.0
3024    3500000.0
Name: price, Length: 3501, dtype: float64

In [64]:
lm.fit(x_train , y_train)

LinearRegression()

In [65]:
lm.intercept_

-358981.17065637605

In [66]:
lm.coef_

array([-8.06500235e+04,  6.02925427e-02,  6.03026866e-02,  5.58831814e-01,
       -2.39168218e+04,  5.17361854e+05,  7.84882197e+05,  7.99094117e+04,
        1.47101808e+05,  1.71545376e+04])

In [67]:
lm.score(x_train , y_train)

0.7847191723786908

In [68]:
lm.score(x_test,y_test)

0.7960383126861529

In [72]:
#saving the model into a pickle file
with open("housepricingModel" , "wb") as f:
    pickle.dump(lm , f)
    

In [73]:
with open("housepricingModel" , "rb") as f:
    md = pickle.load(f)

In [75]:
md.predict([[2,10,3.0,2,1.0,2,5,6,4,3]])

array([5534265.86910494])