In [32]:
#import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
import numpy as np

In [33]:
df_house = pd.read_csv("Housing_data.csv")

In [34]:
df_house.head()

price  bedrooms  bathrooms  toilets  estate_flag  terrace_flag  \
0   850000.0       3.0        2.0      3.0          0.0           0.0   
1   650000.0       1.0        1.0      1.0          1.0           0.0   
2   600000.0       2.0        2.0      2.0          0.0           0.0   
3  1500000.0       3.0        3.0      4.0          1.0           0.0   
4  1500000.0       3.0        3.0      3.0          1.0           0.0   

   new_flag  serviced_flag  location_rank  exec_flag  estate_price  \
0       0.0            0.0           31.0        1.0     1300000.0   
1       1.0            1.0            9.0        1.0      400000.0   
2       0.0            0.0           26.0        1.0      800000.0   
3       0.0            0.0           31.0        2.0     1300000.0   
4       0.0            0.0           31.0        2.0     1300000.0   

   serviced_price  new_price locationbed location  \
0       1840000.0  1840000.0    gbagada3  gbagada   
1        560000.0   560000.0    gbagada1  gbagada   
2       1060000.0  1060000.0    gbagada2  gbagada   
3       1840000.0  1840000.0    gbagada3  gbagada   
4       1840000.0  1840000.0    gbagada3  gbagada   

                          spec_location  \
0          sosanya soluyi gbagada lagos   
1           millenuim ups gbagada lagos   
2                 alapere gbagada lagos   
3                  medina gbagada lagos   
4  adeola atunrase medina gbagada lagos   

                                         description  
0  3 bedroom Flat / Apartment for rent Sosanya So...  
1  1 bedroom mini flat Mini flat Flat / Apartment...  
2          2bed at Alapere, all rooms ensuit ... ...  
3  3 bedroom Flat / Apartment for rent Medina Gba...  
4  3 bedroom House for rent Adeola Atunrase Medin...

In [37]:
df_house[(df_house["location"] == "lekki") & (df_house["price"])]

price  bedrooms  bathrooms  toilets  estate_flag  terrace_flag  \
2279  2000000.0       3.0        3.0      4.0          0.0           0.0   
2280  3500000.0       4.0        4.0      5.0          0.0           1.0   
2281  1400000.0       1.0        1.0      0.0          1.0           0.0   
2282  1600000.0       2.0        2.0      3.0          0.0           0.0   
2283  3000000.0       4.0        5.0      6.0          1.0           1.0   
...         ...       ...        ...      ...          ...           ...   
4372  4000000.0       4.0        4.0      5.0          1.0           0.0   
4373  6000000.0       3.0        3.0      4.0          1.0           1.0   
4374  7000000.0       4.0        5.0      5.0          1.0           1.0   
4375  4500000.0       5.0        5.0      6.0          0.0           1.0   
4376  1200000.0       3.0        3.0      4.0          1.0           0.0   

      new_flag  serviced_flag  location_rank  exec_flag  estate_price  \
2279       0.0            0.0           43.0        2.0     2500000.0   
2280       0.0            0.0           52.0        4.0     3500000.0   
2281       0.0            0.0           25.0        2.0     1000000.0   
2282       1.0            1.0           35.0        2.0     1800000.0   
2283       1.0            0.0           52.0        3.0     3500000.0   
...        ...            ...            ...        ...           ...   
4372       1.0            1.0           52.0        4.0     3500000.0   
4373       1.0            1.0           43.0        4.0     2500000.0   
4374       1.0            1.0           52.0        4.0     3500000.0   
4375       1.0            0.0           60.0        1.0     5000000.0   
4376       1.0            0.0           43.0        2.0     2500000.0   

      serviced_price  new_price locationbed location  \
2279       3500000.0  3500000.0      lekki3    lekki   
2280       4500000.0  4500000.0      lekki4    lekki   
2281       1500000.0  1500000.0      lekki1    lekki   
2282       2500000.0  2500000.0      lekki2    lekki   
2283       4500000.0  4500000.0      lekki4    lekki   
...              ...        ...         ...      ...   
4372       4500000.0  4500000.0      lekki4    lekki   
4373       3500000.0  3500000.0      lekki3    lekki   
4374       4500000.0  4500000.0      lekki4    lekki   
4375       6500000.0  6500000.0      lekki5    lekki   
4376       3500000.0  3500000.0      lekki3    lekki   

                                          spec_location  \
2279                                  ikate lekki lagos   
2280                                  ikota lekki lagos   
2281                          lekki phase 1 lekki lagos   
2282                                  ikota lekki lagos   
2283       ikota villa estate lekki phase 2 lekki lagos   
...                                                 ...   
4372                    marwa lekki phase 1 lekki lagos   
4373            off admiralty lekki phase 1 lekki lagos   
4374            lekki phase 1 lekki phase 1 lekki lagos   
4375                          lekki phase 1 lekki lagos   
4376  mayfair garden estate, awoyaya eputu ibeju lek...   

                                            description  
2279  For more information, pricing and private view...  
2280  4 bedroom Semi Detached Duplex House for rent ...  
2281  For more information, pricing and private view...  
2282  Its a fully serviced apartment with air condit...  
2283  FOR RENT: Brand New Superbly Finished 4 Bedroo...  
...                                                 ...  
4372  It's located in a beautiful mini estate in Lek...  
4373  3 bedroom flat for rent Off admiralty Lekki Ph...  
4374  -Newly built 4 bedroom with a boys quarter. -F...  
4375  Newly built spacious 5bedroom semi detached du...  
4376  Lovely built three bedrooms flat in an estate ...  

[2098 rows x 17 columns]

In [4]:
df_house.drop(["locationbed" , "spec_location" , "description" ] ,  axis = "columns" , inplace = True)

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le

LabelEncoder()

In [6]:
df_house["location"] = le.fit_transform(df_house["location"])

In [7]:
df_house["location"]

0       1
1       1
2       1
3       1
4       1
       ..
4372    6
4373    6
4374    6
4375    6
4376    6
Name: location, Length: 4377, dtype: int32

In [8]:
X = df_house.iloc[: , 1: 14].values
X

array([[3.00e+00, 2.00e+00, 3.00e+00, ..., 1.84e+06, 1.84e+06, 1.00e+00],
       [1.00e+00, 1.00e+00, 1.00e+00, ..., 5.60e+05, 5.60e+05, 1.00e+00],
       [2.00e+00, 2.00e+00, 2.00e+00, ..., 1.06e+06, 1.06e+06, 1.00e+00],
       ...,
       [4.00e+00, 5.00e+00, 5.00e+00, ..., 4.50e+06, 4.50e+06, 6.00e+00],
       [5.00e+00, 5.00e+00, 6.00e+00, ..., 6.50e+06, 6.50e+06, 6.00e+00],
       [3.00e+00, 3.00e+00, 4.00e+00, ..., 3.50e+06, 3.50e+06, 6.00e+00]])

In [9]:
y = df_house.iloc[: , 0]
y

0        850000.0
1        650000.0
2        600000.0
3       1500000.0
4       1500000.0
          ...    
4372    4000000.0
4373    6000000.0
4374    7000000.0
4375    4500000.0
4376    1200000.0
Name: price, Length: 4377, dtype: float64

In [10]:
#features in selection
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [11]:
#apply SelectKBest class to extract top 10 best features
bestfeatures = SelectKBest(score_func=chi2, k=10)
fit = bestfeatures.fit(X,y)
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(df_house.iloc[: , 1:14].columns)

In [12]:
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']  #naming the dataframe columns
print(featureScores.nlargest(10,'Score'))  #print 10 best features

             Specs         Score
10  serviced_price  4.490097e+09
11       new_price  4.490097e+09
9     estate_price  3.648917e+09
7    location_rank  2.479423e+04
8        exec_flag  1.901624e+03
4     terrace_flag  1.644899e+03
2          toilets  1.308640e+03
0         bedrooms  1.246457e+03
1        bathrooms  9.908438e+02
12        location  4.881536e+02


In [13]:
#now getting the my data split
X = df_house[["bathrooms" , "serviced_price" , "new_price" , "estate_price" , "location_rank","exec_flag" , "terrace_flag" , "toilets" , "bedrooms" , "location"]].values
X

array([[2.00e+00, 1.84e+06, 1.84e+06, ..., 3.00e+00, 3.00e+00, 1.00e+00],
       [1.00e+00, 5.60e+05, 5.60e+05, ..., 1.00e+00, 1.00e+00, 1.00e+00],
       [2.00e+00, 1.06e+06, 1.06e+06, ..., 2.00e+00, 2.00e+00, 1.00e+00],
       ...,
       [5.00e+00, 4.50e+06, 4.50e+06, ..., 5.00e+00, 4.00e+00, 6.00e+00],
       [5.00e+00, 6.50e+06, 6.50e+06, ..., 6.00e+00, 5.00e+00, 6.00e+00],
       [3.00e+00, 3.50e+06, 3.50e+06, ..., 4.00e+00, 3.00e+00, 6.00e+00]])

In [14]:
y

0        850000.0
1        650000.0
2        600000.0
3       1500000.0
4       1500000.0
          ...    
4372    4000000.0
4373    6000000.0
4374    7000000.0
4375    4500000.0
4376    1200000.0
Name: price, Length: 4377, dtype: float64

In [15]:
#using the train and split method for modelling 

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import pickle
import joblib

In [16]:
lm = LinearRegression()

In [17]:
x_train , x_test , y_train , y_test = train_test_split(X , y , test_size = 0.2)

In [18]:
x_train

array([[3.0e+00, 3.5e+06, 3.5e+06, ..., 4.0e+00, 3.0e+00, 6.0e+00],
       [3.0e+00, 1.0e+06, 1.0e+06, ..., 3.0e+00, 2.0e+00, 9.0e+00],
       [3.0e+00, 1.5e+06, 1.5e+06, ..., 4.0e+00, 3.0e+00, 0.0e+00],
       ...,
       [1.0e+00, 6.6e+05, 6.6e+05, ..., 1.0e+00, 1.0e+00, 8.0e+00],
       [2.0e+00, 6.6e+05, 6.6e+05, ..., 2.0e+00, 1.0e+00, 8.0e+00],
       [5.0e+00, 7.5e+06, 7.5e+06, ..., 4.0e+00, 4.0e+00, 4.0e+00]])

In [19]:
y_train

3457    2000000.0
729     1200000.0
2215    1000000.0
769      500000.0
962      700000.0
          ...    
3307    3000000.0
2613    3000000.0
479      600000.0
329      500000.0
1682    5000000.0
Name: price, Length: 3501, dtype: float64

In [20]:
lm.fit(x_train , y_train)

LinearRegression()

In [21]:
lm.intercept_

-302244.675357013

In [22]:
lm.coef_

array([-8.16170943e+04,  4.50510689e-02,  4.50762655e-02,  6.21320599e-01,
       -2.41218878e+04,  5.09418963e+05,  7.93848959e+05,  9.40059054e+04,
        1.05139747e+05,  1.60365579e+04])

In [23]:
lm.score(x_train , y_train)

0.7851074676396741

In [24]:
lm.score(x_test,y_test)

0.7943840600577045

In [25]:
import pickle
import joblib

In [26]:
filename = "housePricing.pkl"
joblib.dump(lm , filename)

['housePricing.pkl']