<h2>Naive Bayes Classifier</h2>

In [24]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [5]:
df = pd.read_csv("py-master/ML/14_naive_bayes/titanic.csv")
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [6]:
df.drop(["PassengerId","Name" ,"SibSp","Parch","Ticket","Cabin","Embarked"] ,  axis = "columns" , inplace = True)
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [7]:
target = df.Survived
inputs = df.drop("Survived" , axis = "columns")

In [8]:
dummy = pd.get_dummies(df.Sex)
dummy

female  male
0         0     1
1         1     0
2         1     0
3         1     0
4         0     1
..      ...   ...
886       0     1
887       1     0
888       1     0
889       0     1
890       0     1

[891 rows x 2 columns]

In [9]:
inputs = pd.concat([inputs,dummy] , axis = "columns")
inputs

Pclass     Sex   Age     Fare  female  male
0         3    male  22.0   7.2500       0     1
1         1  female  38.0  71.2833       1     0
2         3  female  26.0   7.9250       1     0
3         1  female  35.0  53.1000       1     0
4         3    male  35.0   8.0500       0     1
..      ...     ...   ...      ...     ...   ...
886       2    male  27.0  13.0000       0     1
887       1  female  19.0  30.0000       1     0
888       3  female   NaN  23.4500       1     0
889       1    male  26.0  30.0000       0     1
890       3    male  32.0   7.7500       0     1

[891 rows x 6 columns]

In [10]:
inputs.drop("Sex" , axis = "columns" , inplace = True)

In [11]:
inputs

Pclass   Age     Fare  female  male
0         3  22.0   7.2500       0     1
1         1  38.0  71.2833       1     0
2         3  26.0   7.9250       1     0
3         1  35.0  53.1000       1     0
4         3  35.0   8.0500       0     1
..      ...   ...      ...     ...   ...
886       2  27.0  13.0000       0     1
887       1  19.0  30.0000       1     0
888       3   NaN  23.4500       1     0
889       1  26.0  30.0000       0     1
890       3  32.0   7.7500       0     1

[891 rows x 5 columns]

In [12]:
#checking for any null values
inputs.isnull().sum()

Pclass      0
Age       177
Fare        0
female      0
male        0
dtype: int64

In [13]:
#clearing the null values in the age columns 
mean = inputs.Age.mean()
mean

29.69911764705882

In [14]:
#Using fillna to replace null values
inputs.Age = inputs.Age.fillna(mean)
inputs.head()

Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [15]:
#checks to see if there are null values
inputs.isnull().sum()

Pclass    0
Age       0
Fare      0
female    0
male      0
dtype: int64

In [16]:
#using the train-test-splits method

X_train , X_test , Y_train , Y_test = train_test_split(inputs , target , test_size = 0.2)

In [17]:
from sklearn.naive_bayes import GaussianNB

In [18]:
GB = GaussianNB()

In [19]:
GB

GaussianNB()

In [20]:
GB.fit(X_train , Y_train)

GaussianNB()

In [21]:
GB.score(X_test , Y_test)

0.7988826815642458

In [22]:
GB.predict(X_test[:10])

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0], dtype=int64)

In [23]:
GB.predict_proba(X_test[:10])

array([[0.9903809 , 0.0096191 ],
       [0.99102437, 0.00897563],
       [0.96719983, 0.03280017],
       [0.98060611, 0.01939389],
       [0.04846986, 0.95153014],
       [0.09618682, 0.90381318],
       [0.98033443, 0.01966557],
       [0.97260215, 0.02739785],
       [0.81974343, 0.18025657],
       [0.97850147, 0.02149853]])

<h2> PART TWO </h2>

In [24]:
df2 = pd.read_csv("py-master/ML/14_naive_bayes/spam.csv")
df2.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [25]:
df2["spam"] = df2["Category"].apply(lambda x: 1 if x =="spam" else 0)
df2

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [26]:
df2.drop("Category" , axis = "columns" , inplace = True)

In [27]:
df2

Message  spam
0     Go until jurong point, crazy.. Available only ...     0
1                         Ok lar... Joking wif u oni...     0
2     Free entry in 2 a wkly comp to win FA Cup fina...     1
3     U dun say so early hor... U c already then say...     0
4     Nah I don't think he goes to usf, he lives aro...     0
...                                                 ...   ...
5567  This is the 2nd time we have tried 2 contact u...     1
5568               Will ü b going to esplanade fr home?     0
5569  Pity, * was in mood for that. So...any other s...     0
5570  The guy did some bitching but I acted like i'd...     0
5571                         Rofl. Its true to its name     0

[5572 rows x 2 columns]

In [28]:
#import library that will convert words to numbers

from sklearn.feature_extraction.text import CountVectorizer

In [29]:
CV = CountVectorizer()

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train , X_test , y_train ,y_test = train_test_split(df2.Message , df2.spam , test_size = 0.25)

In [32]:
len(X_train)

4179

In [33]:
len(y_train)

4179

In [34]:
from sklearn.naive_bayes import MultinomialNB

In [35]:
MB = MultinomialNB()

In [36]:
#using pipelines
from sklearn.pipeline import Pipeline

In [37]:
clf = Pipeline([
    ("countvectorizer" , CountVectorizer()),
    ("multinomial" , MultinomialNB())
])

In [38]:
clf.fit(X_train , y_train)

Pipeline(steps=[('countvectorizer', CountVectorizer()),
                ('multinomial', MultinomialNB())])

In [40]:
clf.score(X_test,y_test)

0.9849246231155779

<h2>Exercise</h2>

In [6]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split

In [7]:
lw = load_wine()

In [8]:
dir(lw)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [13]:
lw.data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [12]:
lw.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [9]:
#train_test_split data
X_train , X_test , y_train , y_test = train_test_split(lw.data , lw.target , test_size = 0.2)

In [10]:
len(X_train)

142

In [11]:
len(X_test)

36

In [20]:
#create a pipeline
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import GaussianNB , MultinomialNB
from sklearn.model_selection import cross_val_score


In [18]:
GN = GaussianNB()
MNB = MultinomialNB()

In [19]:
GN.fit(X_train , y_train)

GaussianNB()

In [31]:
cvs_gn = cross_val_score(GN, lw.data , lw.target ,cv = 5, scoring = "accuracy")

In [32]:
np.average(cvs_gn)

0.9663492063492063

In [33]:
 cvs_mnb= cross_val_score(MNB, lw.data , lw.target ,cv = 5, scoring = "accuracy")

In [34]:
np.average(cvs)

0.843968253968254